# Generated by Django 4.2 on 2023-05-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='business_id',
            new_name='id',
        ),
    ]
