# Generated by Django 4.2 on 2023-04-13 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusnessAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kifle_ketema', models.CharField(max_length=25)),
                ('woreda', models.CharField(max_length=20)),
                ('kebele', models.CharField(max_length=5)),
                ('house_number', models.CharField(max_length=20)),
                ('frendly_BN', models.CharField(max_length=50)),
                ('business_phone', models.CharField(max_length=12)),
                ('business_email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(choices=[('Passport', 'Passport'), ('Driver License', 'Driver License'), ('kebele ID', 'kebele ID'), ('National ID', 'National ID')], max_length=20)),
                ('id_upload', models.ImageField(upload_to='ids/')),
            ],
        ),
        migrations.CreateModel(
            name='Incorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorp_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='business_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='VerifyBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=30)),
                ('staff_size', models.CharField(choices=[('1-5 People', '1-5 People'), ('5-10 People', '5-10 People'), ('More Than 10 People', 'More Than 10 People')], max_length=30)),
                ('trans_volume', models.CharField(choices=[('10,000 - 100,000', '10,000 - 100,000'), ('100,000 - 500,000', '100,000 - 500,000'), ('More Than 500,000', 'More Than 500,000')], max_length=30)),
                ('legal_BN', models.CharField(max_length=50)),
                ('tin_numbers', models.CharField(max_length=50)),
                ('vat_check', models.BooleanField(default=False)),
                ('business_reg_num', models.CharField(max_length=30)),
                ('trade_license', models.FileField(upload_to='trade_license/')),
                ('tin_certificate', models.FileField(upload_to='tin_certificate/')),
                ('memorandum', models.FileField(upload_to='memorandum/')),
                ('business_contact', models.CharField(max_length=30)),
                ('proof_address', models.FileField(upload_to='address_proof/')),
                ('business_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.busnessadress')),
                ('incorp_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incorporation_name', to='accounts.incorporation')),
                ('industrys', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industrys', to='accounts.industry')),
            ],
        ),
        migrations.CreateModel(
            name='PesonalAdderss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state', to='accounts.states')),
            ],
        ),
        migrations.CreateModel(
            name='DedicatedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('date_of_birth', models.DateField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_adress', to='accounts.pesonaladderss')),
                ('id_docouments', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_docouments', to='accounts.iddocument')),
            ],
        ),
        migrations.AddField(
            model_name='busnessadress',
            name='states',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='accounts.states'),
        ),
    ]
