# Generated by Django 4.2 on 2023-04-14 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_busnessadress_iddocument_incorporation_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesonaladderss',
            name='state',
        ),
        migrations.RemoveField(
            model_name='dedicatedperson',
            name='address',
        ),
        migrations.RemoveField(
            model_name='dedicatedperson',
            name='id_docouments',
        ),
        migrations.AddField(
            model_name='dedicatedperson',
            name='full_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dedicatedperson',
            name='id_upload',
            field=models.ImageField(null=True, upload_to='ids/'),
        ),
        migrations.AddField(
            model_name='dedicatedperson',
            name='ids',
            field=models.CharField(choices=[('Passport', 'Passport'), ('Driver License', 'Driver License'), ('kebele ID', 'kebele ID'), ('National ID', 'National ID')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dedicatedperson',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state', to='accounts.states'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='IdDocument',
        ),
        migrations.DeleteModel(
            name='PesonalAdderss',
        ),
    ]
