# Generated by Django 4.2 on 2023-04-15 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_pesonaladderss_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=30)),
                ('staff_size', models.CharField(choices=[('1-5 People', '1-5 People'), ('5-10 People', '5-10 People'), ('More Than 10 People', 'More Than 10 People')], max_length=30)),
                ('trans_volume', models.CharField(choices=[('10,000 - 100,000', '10,000 - 100,000'), ('100,000 - 500,000', '100,000 - 500,000'), ('More Than 500,000', 'More Than 500,000')], max_length=30)),
                ('legal_BN', models.CharField(max_length=50)),
                ('tin_numbers', models.CharField(max_length=50)),
                ('vat_check', models.BooleanField(default=False)),
                ('business_reg_num', models.CharField(max_length=30)),
                ('trade_license', models.FileField(upload_to='trade_license/')),
                ('tin_certificate', models.FileField(upload_to='tin_certificate/')),
                ('memorandum', models.FileField(upload_to='memorandum/')),
                ('business_contact', models.CharField(max_length=30)),
                ('proof_address', models.FileField(upload_to='address_proof/')),
                ('kifle_ketema', models.CharField(max_length=25)),
                ('woreda', models.CharField(max_length=20)),
                ('kebele', models.CharField(max_length=5)),
                ('house_number', models.CharField(max_length=20)),
                ('frendly_BN', models.CharField(max_length=50)),
                ('business_phone', models.CharField(max_length=12)),
                ('business_email', models.EmailField(max_length=255, unique=True)),
                ('incorp_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incorporation_name', to='accounts.incorporation')),
                ('industrys', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industrys', to='accounts.industry')),
                ('states', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='accounts.states')),
            ],
        ),
        migrations.RemoveField(
            model_name='verifybusiness',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='verifybusiness',
            name='incorp_type',
        ),
        migrations.RemoveField(
            model_name='verifybusiness',
            name='industrys',
        ),
        migrations.DeleteModel(
            name='BusnessAdress',
        ),
        migrations.DeleteModel(
            name='VerifyBusiness',
        ),
    ]
