# Generated by Django 4.2 on 2023-05-15 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_verifydocument_user_utility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifydocument',
            name='user',
        ),
        migrations.CreateModel(
            name='UserWithBusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_with_business_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
