# Generated by Django 4.2 on 2023-04-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_dedicatedperson_id_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedicatedperson',
            name='id_upload',
            field=models.ImageField(upload_to='data/ids/'),
        ),
        migrations.AlterField(
            model_name='dedicatedperson',
            name='ids',
            field=models.CharField(choices=[('Passport', 'Passport'), ('Driver License', 'Driver License'), ('kebele ID', 'kebele ID'), ('National ID', 'National ID')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dedicatedperson',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state', to='accounts.states'),
        ),
        migrations.AlterField(
            model_name='verifydocument',
            name='memorandum',
            field=models.FileField(upload_to='data/memorandum/'),
        ),
    ]
