# Generated by Django 4.2 on 2023-05-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_verifydocument_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='business_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
