# Generated by Django 4.2 on 2023-05-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useraccount_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='business_type',
            field=models.BooleanField(default=True),
        ),
    ]
