# Generated by Django 4.2 on 2023-05-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_useraccount_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='utility',
            name='bill_amount',
        ),
        migrations.AddField(
            model_name='utility',
            name='is_flexible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='bill_type',
            field=models.ManyToManyField(related_name='bill_type', to='accounts.billtype'),
        ),
    ]
