# Generated by Django 4.2 on 2023-05-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_billtype_remove_utility_bill_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
