# Generated by Django 4.2 on 2023-05-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_utility_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityNormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('custemer', models.CharField(max_length=255, null=True)),
                ('bill_type', models.CharField(max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='utility',
            name='is_flexible',
        ),
        migrations.AddField(
            model_name='verifydocument',
            name='is_flexible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='verifydocument',
            name='is_utility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billtype',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
