# Generated by Django 4.2 on 2023-05-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='banks',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
