# Generated by Django 4.2 on 2023-05-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customer_remove_utilitynormal_custemer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utility',
            name='bill_type',
        ),
        migrations.RemoveField(
            model_name='utilitynormal',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='verifydocument',
            name='is_flexible',
        ),
        migrations.DeleteModel(
            name='BillType',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Utility',
        ),
        migrations.DeleteModel(
            name='UtilityNormal',
        ),
    ]
