# Generated by Django 4.2 on 2023-05-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_banks_is_verified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banks',
            new_name='BanksConnected',
        ),
    ]
