# Generated by Django 4.2 on 2023-06-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_utility_bill_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_sizes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_volume', models.CharField(max_length=255)),
            ],
        ),
    ]
