# Generated by Django 4.2 on 2023-05-01 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_connectedbanks_delete_banksconnected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedbanks',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_banks', to=settings.AUTH_USER_MODEL),
        ),
    ]
